//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNS.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTBCNOCONG
    {
        public string MaBC { get; set; }
        public string MaKH { get; set; }
        public Nullable<decimal> NoDau { get; set; }
        public Nullable<decimal> NoCuoi { get; set; }
        public Nullable<decimal> PhatSinh { get; set; }
    
        public virtual BaoCao BaoCao { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
