//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNS.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTHD
    {
        public string MaHD { get; set; }
        public string MaSach { get; set; }
        public Nullable<int> SoLuongBan { get; set; }
        public Nullable<decimal> DonGiaBan { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
        public virtual Sach Sach { get; set; }
    }
}
